package com.jtdd.entity;
// Generated 2017-11-4 17:55:03 by Hibernate Tools 4.0.1.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * AllScorse generated by hbm2java
 */
@Entity
@Table(name = "all_scorse", catalog = "stms")
public class AllScorse implements java.io.Serializable {

	private Integer id;
	private int userId;
	private int totalPoints;
	private int honestPoints;
	private int executePoints;
	private int teamPoints;
	private int skillPoints;
	private int healthPoints;
	private String classRanking;
	private String majorRanking;
	private String departmentRanking;
	private String other;
	
	public AllScorse() {
	}

	public AllScorse(int userId, int totalPoints, int honestPoints, int executePoints, int teamPoints, int skillPoints,
			int healthPoints, String classRanking, String majorRanking, String departmentRanking,String other) {
		this.userId = userId;
		this.totalPoints = totalPoints;
		this.honestPoints = honestPoints;
		this.executePoints = executePoints;
		this.teamPoints = teamPoints;
		this.skillPoints = skillPoints;
		this.healthPoints = healthPoints;
		this.classRanking = classRanking;
		this.majorRanking = majorRanking;
		this.departmentRanking = departmentRanking;
		this.other = other;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "user_id", nullable = false)
	public int getUserId() {
		return this.userId;
	}

	public void setUserId(int userId) {
		this.userId = userId;
	}

	@Column(name = "total_points", nullable = false)
	public int getTotalPoints() {
		return this.totalPoints;
	}

	public void setTotalPoints(int totalPoints) {
		this.totalPoints = totalPoints;
	}

	@Column(name = "honest_points", nullable = false)
	public int getHonestPoints() {
		return this.honestPoints;
	}

	public void setHonestPoints(int honestPoints) {
		this.honestPoints = honestPoints;
	}

	@Column(name = "execute_points", nullable = false)
	public int getExecutePoints() {
		return this.executePoints;
	}

	public void setExecutePoints(int executePoints) {
		this.executePoints = executePoints;
	}

	@Column(name = "team_points", nullable = false)
	public int getTeamPoints() {
		return this.teamPoints;
	}

	public void setTeamPoints(int teamPoints) {
		this.teamPoints = teamPoints;
	}

	@Column(name = "skill_points", nullable = false)
	public int getSkillPoints() {
		return this.skillPoints;
	}

	public void setSkillPoints(int skillPoints) {
		this.skillPoints = skillPoints;
	}

	@Column(name = "health_points", nullable = false)
	public int getHealthPoints() {
		return this.healthPoints;
	}

	public void setHealthPoints(int healthPoints) {
		this.healthPoints = healthPoints;
	}

	@Column(name = "class_ranking", nullable = false, length = 50)
	public String getClassRanking() {
		return this.classRanking;
	}

	public void setClassRanking(String classRanking) {
		this.classRanking = classRanking;
	}

	@Column(name = "major_ranking", nullable = false, length = 50)
	public String getMajorRanking() {
		return this.majorRanking;
	}

	public void setMajorRanking(String majorRanking) {
		this.majorRanking = majorRanking;
	}

	@Column(name = "department_ranking", nullable = false, length = 50)
	public String getDepartmentRanking() {
		return this.departmentRanking;
	}

	public void setDepartmentRanking(String departmentRanking) {
		this.departmentRanking = departmentRanking;
	}
	
	@Column(name = "other", length = 50)
	public String getOther() {
		return other;
	}

	public void setOther(String other) {
		this.other = other;
	}
	
}
