package com.jtdd.entity;
// Generated 2017-11-4 17:55:03 by Hibernate Tools 4.0.1.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Executes generated by hbm2java
 */
@Entity
@Table(name = "executes", catalog = "stms")
public class Executes implements java.io.Serializable {

	private Integer id;
	private Rules rules;
	private String studentNumber;
	private String studentName;
	private int menuId;
	private String descript;
	private int statusId;
	private Date recordTime;

	public Executes() {
	}

	public Executes(Integer id, Rules rules,String studentNumber, String studentName, int menuId,String descript, int statusId, Date recordTime) {
		this.id = id;
		this.rules = rules;
		this.studentNumber = studentNumber;
		this.studentName = studentName;
		this.menuId = menuId;
		this.descript = descript;
		this.statusId = statusId;
		this.recordTime = recordTime;
	}
	
	public Executes(Rules rules, String studentNumber, String studentName, int menuId, int statusId, Date recordTime) {
		this.rules = rules;
		this.studentNumber = studentNumber;
		this.studentName = studentName;
		this.menuId = menuId;
		this.statusId = statusId;
		this.recordTime = recordTime;
	}


	public Executes(Rules rules, String studentNumber, String studentName, int menuId, String descript, int statusId,
			Date recordTime) {
		this.rules = rules;
		this.studentNumber = studentNumber;
		this.studentName = studentName;
		this.menuId = menuId;
		this.descript = descript;
		this.statusId = statusId;
		this.recordTime = recordTime;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "rules_id", nullable = false)
	public Rules getRules() {
		return this.rules;
	}

	public void setRules(Rules rules) {
		this.rules = rules;
	}

	@Column(name = "student_number", nullable = false, length = 50)
	public String getStudentNumber() {
		return this.studentNumber;
	}

	public void setStudentNumber(String studentNumber) {
		this.studentNumber = studentNumber;
	}

	@Column(name = "student_name", nullable = false, length = 50)
	public String getStudentName() {
		return this.studentName;
	}

	public void setStudentName(String studentName) {
		this.studentName = studentName;
	}

	@Column(name = "menu_id", nullable = false)
	public int getMenuId() {
		return this.menuId;
	}

	public void setMenuId(int menuId) {
		this.menuId = menuId;
	}

	@Column(name = "descript", length = 50)
	public String getDescript() {
		return this.descript;
	}

	public void setDescript(String descript) {
		this.descript = descript;
	}

	@Column(name = "status_id", nullable = false)
	public int getStatusId() {
		return this.statusId;
	}

	public void setStatusId(int statusId) {
		this.statusId = statusId;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "record_time", nullable = false, length = 10)
	public Date getRecordTime() {
		return this.recordTime;
	}

	public void setRecordTime(Date recordTime) {
		this.recordTime = recordTime;
	}

}
