package com.jtdd.entity;
// Generated 2017-11-4 17:55:03 by Hibernate Tools 4.0.1.Final

import java.util.Collection;
import java.util.Date;
import java.util.Set;

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.Transient;

/**
 * Honest generated by hbm2java
 */
@Entity
@Table(name = "honest", catalog = "stms")
public class Honest implements java.io.Serializable {

	private Integer id;
	private Rules rules;
	private int menuId;
	private String studentName;
	private String studentNumber;
	private String remarks;
	private int statusId;
	private Date recordTime;
	public Honest() {
	}
	
	public Honest(String studentName, String studentNumber, String remarks, Date recordTime) {
		super();
		this.studentName = studentName;
		this.studentNumber = studentNumber;
		this.remarks = remarks;
		this.recordTime = recordTime;
	}
	

	public Honest(Integer id, Rules rules, String studentName, String studentNumber, String remarks, Date recordTime) {
		super();
		this.id = id;
		this.rules = rules;
		this.studentName = studentName;
		this.studentNumber = studentNumber;
		this.remarks = remarks;
		this.recordTime = recordTime;
	}

	public Honest(Integer id, String studentName, String studentNumber, String remarks, Date recordTime) {
		super();
		this.id = id;
		this.studentName = studentName;
		this.studentNumber = studentNumber;
		this.remarks = remarks;
		this.recordTime = recordTime;
	}

	public Honest(Rules rules, int menuId, String studentName, String studentNumber, String remarks, int statusId,
			Date recordTime) {
		this.rules = rules;
		this.menuId = menuId;
		this.studentName = studentName;
		this.studentNumber = studentNumber;
		this.remarks = remarks;
		this.statusId = statusId;
		this.recordTime = recordTime;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY,cascade=(CascadeType.ALL))
	@JoinColumn(name = "rule_id", nullable = false)
	public Rules getRules() {
		return this.rules;
	}

	public void setRules(Rules rules) {
		this.rules = rules;
	}

	@Column(name = "menu_id", nullable = false)
	public int getMenuId() {
		return this.menuId;
	}

	public void setMenuId(int menuId) {
		this.menuId = menuId;
	}

	@Column(name = "student_name", nullable = false, length = 50)
	public String getStudentName() {
		return this.studentName;
	}

	public void setStudentName(String studentName) {
		this.studentName = studentName;
	}

	@Column(name = "student_number", nullable = false, length = 50)
	public String getStudentNumber() {
		return this.studentNumber;
	}

	public void setStudentNumber(String studentNumber) {
		this.studentNumber = studentNumber;
	}

	@Column(name = "remarks", nullable = false, length = 50)
	public String getRemarks() {
		return this.remarks;
	}

	public void setRemarks(String remarks) {
		this.remarks = remarks;
	}

	@Column(name = "status_id", nullable = false)
	public int getStatusId() {
		return this.statusId;
	}

	public void setStatusId(int statusId) {
		this.statusId = statusId;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "record_time", nullable = false, length = 10)
	public Date getRecordTime() {
		return this.recordTime;
	}

	public void setRecordTime(Date recordTime) {
		this.recordTime = recordTime;
	}
		
}
