package com.jtdd.entity;
// Generated 2017-11-4 17:55:03 by Hibernate Tools 4.0.1.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

import org.codehaus.jackson.annotate.JsonManagedReference;

/**
 * LoginRole generated by hbm2java
 */
@Entity
@Table(name = "login_role", catalog = "stms")
public class LoginRole implements java.io.Serializable {

	private Integer id;
	@JsonManagedReference
	private Role role;
	@JsonManagedReference
	private Login login;
	public LoginRole() {
	}

	public LoginRole(Role role, Login login) {
		this.role = role;
		this.login = login;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "role_id", nullable = false)
	public Role getRole() {
		return this.role;
	}

	public void setRole(Role role) {
		this.role = role;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "loin_id", nullable = false)
	public Login getLogin() {
		return this.login;
	}

	public void setLogin(Login login) {
		this.login = login;
	}

	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((id == null) ? 0 : id.hashCode());
		result = prime * result + ((login == null) ? 0 : login.hashCode());
		result = prime * result + ((role == null) ? 0 : role.hashCode());
		return result;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj){
			return true;
		}
			
		if (obj == null){
			return false;
		}
			
		if (getClass() != obj.getClass()) {
			return false;
		}
			
		LoginRole other = (LoginRole) obj;
		if (id == null) {
			if (other.id != null) {
				return false;
			}
				
		} else if (!id.equals(other.id)) {
			return false;
		}
			
		if (login == null) {
			if (other.login != null) {
				return false;
			}
				
		} else if (!login.equals(other.login)) {
			return false;
		}
			
		if (role == null) {
			if (other.role != null) {
				return false;
			}
				
		} else if (!role.equals(other.role)) {
			return false;
		}
			
		return true;
	}
	
	
}
