package com.jtdd.entity;
// Generated 2017-11-4 17:55:03 by Hibernate Tools 4.0.1.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import org.codehaus.jackson.annotate.JsonIgnore;

import com.fasterxml.jackson.annotation.JsonBackReference;


/**
 * Login generated by hbm2java
 */
@Entity
@Table(name = "login", catalog = "stms")
public class Login implements java.io.Serializable {

	private Integer loginId;
	private String loginName;
	private String loginPassword;
	private Date loginTime;
	private String loginIp;
	private Date loginLeaveTime;
	private int loginUserId;
	@JsonBackReference
	private Set<LoginRole> loginRoles = new HashSet<LoginRole>(0);

	public Login() {
	}

	public Login(String loginName, String loginPassword, Date loginTime, String loginIp, int loginUserId) {
		this.loginName = loginName;
		this.loginPassword = loginPassword;
		this.loginTime = loginTime;
		this.loginIp = loginIp;
		this.loginUserId = loginUserId;
	}

	public Login(String loginName, String loginPassword, Date loginTime, String loginIp, Date loginLeaveTime,
			int loginUserId, Set<LoginRole> loginRoles) {
		this.loginName = loginName;
		this.loginPassword = loginPassword;
		this.loginTime = loginTime;
		this.loginIp = loginIp;
		this.loginLeaveTime = loginLeaveTime;
		this.loginUserId = loginUserId;
		this.loginRoles = loginRoles;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "login_Id", unique = true, nullable = false)
	public Integer getLoginId() {
		return this.loginId;
	}

	public void setLoginId(Integer loginId) {
		this.loginId = loginId;
	}

	@Column(name = "login_name", nullable = false, length = 50)
	public String getLoginName() {
		return this.loginName;
	}

	public void setLoginName(String loginName) {
		this.loginName = loginName;
	}

	@Column(name = "login_password", nullable = false, length = 50)
	public String getLoginPassword() {
		return this.loginPassword;
	}

	public void setLoginPassword(String loginPassword) {
		this.loginPassword = loginPassword;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "login_time", nullable = false, length = 10)
	public Date getLoginTime() {
		return this.loginTime;
	}

	public void setLoginTime(Date loginTime) {
		this.loginTime = loginTime;
	}

	@Column(name = "login_ip", nullable = false, length = 50)
	public String getLoginIp() {
		return this.loginIp;
	}

	public void setLoginIp(String loginIp) {
		this.loginIp = loginIp;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "login_leave_time", length = 10)
	public Date getLoginLeaveTime() {
		return this.loginLeaveTime;
	}

	public void setLoginLeaveTime(Date loginLeaveTime) {
		this.loginLeaveTime = loginLeaveTime;
	}

	@Column(name = "login_user_id", nullable = false)
	public int getLoginUserId() {
		return this.loginUserId;
	}

	public void setLoginUserId(int loginUserId) {
		this.loginUserId = loginUserId;
	}
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "login")
	public Set<LoginRole> getLoginRoles() {
		return this.loginRoles;
	}
	
	public void setLoginRoles(Set<LoginRole> loginRoles) {
		this.loginRoles = loginRoles;
	}

}
