package com.jtdd.entity;
// Generated 2017-11-4 17:55:03 by Hibernate Tools 4.0.1.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

import org.codehaus.jackson.annotate.JsonManagedReference;

import com.fasterxml.jackson.annotation.JsonBackReference;
import com.fasterxml.jackson.annotation.JsonIgnore;

/**
 * Major generated by hbm2java
 */
@Entity
@Table(name = "major", catalog = "stms")
public class Major implements java.io.Serializable {

	private Integer id;
	@JsonManagedReference
	private StudentDepartment studentDepartment;
	private String name;
	private int classCount;
	@JsonManagedReference
	private Set<StudentClass> studentClass = new HashSet<StudentClass>(0);

	public Major() {
	}

	public Major(Integer id, String name) {
		this.id = id;
		this.name = name;
	}
	
	public Major(StudentDepartment studentDepartment, String name, int classCount) {
		this.studentDepartment = studentDepartment;
		this.name = name;
		this.classCount = classCount;
	}

	public Major(StudentDepartment studentDepartment, String name, int classCount, Set<StudentClass> studentClass) {
		this.studentDepartment = studentDepartment;
		this.name = name;
		this.classCount = classCount;
		this.studentClass = studentClass;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "department_id", nullable = false)
	public StudentDepartment getStudentDepartment() {
		return this.studentDepartment;
	}

	public void setStudentDepartment(StudentDepartment studentDepartment) {
		this.studentDepartment = studentDepartment;
	}

	@Column(name = "name", nullable = false, length = 50)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "class_count", nullable = false)
	public int getClassCount() {
		return this.classCount;
	}

	public void setClassCount(int classCount) {
		this.classCount = classCount;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "major")
	public Set<StudentClass> getstudentClass() {
		return this.studentClass;
	}

	public void setstudentClass(Set<StudentClass> studentClass) {
		this.studentClass = studentClass;
	}

}
