package com.jtdd.entity;
// Generated 2017-11-25 20:56:48 by Hibernate Tools 4.0.1.Final


import java.util.HashSet;
import java.util.List;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Transient;

import com.fasterxml.jackson.annotation.JsonBackReference;

/**
 * Menu generated by hbm2java
 */
@Entity
@Table(name = "menu", catalog = "stms")
public class Menu implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Integer menuId;
	private String menuName;
	private int menuFatherId;
	private int menuGrade;
	private String menuUrl;
	@JsonBackReference
	private Set<MenuRole> menuRoles = new HashSet<MenuRole>(0);
	
	
	private List<Menu> childmenus;
	@Transient 
	public List<Menu> getChildmenus() {
		return childmenus;
	}

	public void setChildmenus(List<Menu> childmenus) {
		this.childmenus = childmenus;
	}

	public Menu() {
	}

	public Menu(String menuName, int menuFatherId, int menuGrade) {
		this.menuName = menuName;
		this.menuFatherId = menuFatherId;
		this.menuGrade = menuGrade;
	}

	public Menu(String menuName, int menuFatherId, int menuGrade, Set<MenuRole> menuRoles) {
		this.menuName = menuName;
		this.menuFatherId = menuFatherId;
		this.menuGrade = menuGrade;
		this.menuRoles = menuRoles;
	}
	//
	public Menu(String menuName, int menuFatherId, int menuGrade,String menuUrl, Set<MenuRole> menuRoles) {
		this.menuName = menuName;
		this.menuFatherId = menuFatherId;
		this.menuGrade = menuGrade;
		this.menuUrl = menuUrl;
		this.menuRoles = menuRoles;
	}
	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "menu_id", unique = true, nullable = false)
	public Integer getMenuId() {
		return this.menuId;
	}

	public void setMenuId(Integer menuId) {
		this.menuId = menuId;
	}

	@Column(name = "menu_name", nullable = false, length = 50)
	public String getMenuName() {
		return this.menuName;
	}

	public void setMenuName(String menuName) {
		this.menuName = menuName;
	}

	@Column(name = "menu_father_id", nullable = false)
	public int getMenuFatherId() {
		return this.menuFatherId;
	}

	public void setMenuFatherId(int menuFatherId) {
		this.menuFatherId = menuFatherId;
	}

	@Column(name = "menu_grade", nullable = false)
	public int getMenuGrade() {
		return this.menuGrade;
	}

	public void setMenuGrade(int menuGrade) {
		this.menuGrade = menuGrade;
	}
	
	@Column(name = "menu_url", nullable = true)
	public String getMenuUrl() {
		return menuUrl;
	}

	public void setMenuUrl(String menuUrl) {
		this.menuUrl = menuUrl;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "menu")
	public Set<MenuRole> getMenuRoles() {
		return this.menuRoles;
	}

	public void setMenuRoles(Set<MenuRole> menuRoles) {
		this.menuRoles = menuRoles;
	}

	@Override
	public boolean equals(Object obj) {
		// TODO Auto-generated method stub
		Menu menu = (Menu) obj;
		if(this.menuId.equals(menu.getMenuId())){
			return true;
		}else{
			return false;
		}
	}
	
}
