package com.jtdd.entity;
// Generated 2017-11-4 17:55:03 by Hibernate Tools 4.0.1.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

import org.codehaus.jackson.annotate.JsonIgnore;
import org.codehaus.jackson.annotate.JsonManagedReference;

import com.fasterxml.jackson.annotation.JsonBackReference;

/**
 * Role generated by hbm2java
 */
@Entity
@Table(name = "role", catalog = "stms")
public class Role implements java.io.Serializable {

	private Integer roleId;
	private String roleName;
	@JsonBackReference
	private Set<MenuRole> menuRoles = new HashSet<MenuRole>(0);
	private Set<UserDetailed> userDetaileds = new HashSet<UserDetailed>(0);
	private Set<LoginRole> loginRoles = new HashSet<LoginRole>(0);
	@JsonBackReference
	private Set<RoleAuthRelation> roleAuthRelations = new HashSet<RoleAuthRelation>(0);
	public Role() {
	}

	public Role(String roleName) {
		this.roleName = roleName;
	}


	public Role(String roleName, Set<MenuRole> menuRoles, Set<UserDetailed> userDetaileds, Set<LoginRole> loginRoles,
			Set<RoleAuthRelation> roleAuthRelations) {
		this.roleName = roleName;
		this.menuRoles = menuRoles;
		this.userDetaileds = userDetaileds;
		this.loginRoles = loginRoles;
		this.roleAuthRelations = roleAuthRelations;
	}
	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "role_Id", unique = true, nullable = false)
	public Integer getRoleId() {
		return this.roleId;
	}

	public void setRoleId(Integer roleId) {
		this.roleId = roleId;
	}

	@Column(name = "role_name", nullable = false, length = 50)
	public String getRoleName() {
		return this.roleName;
	}

	public void setRoleName(String roleName) {
		this.roleName = roleName;
	}
	
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "role")
	public Set<MenuRole> getMenuRoles() {
		return this.menuRoles;
	}

	public void setMenuRoles(Set<MenuRole> menuRoles) {
		this.menuRoles = menuRoles;
	}
	
	@JsonBackReference
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "role")
	public Set<UserDetailed> getUserDetaileds() {
		return this.userDetaileds;
	}

	public void setUserDetaileds(Set<UserDetailed> userDetaileds) {
		this.userDetaileds = userDetaileds;
	}
	@JsonBackReference
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "role")
	public Set<LoginRole> getLoginRoles() {
		return this.loginRoles;
	}

	public void setLoginRoles(Set<LoginRole> loginRoles) {
		this.loginRoles = loginRoles;
	}
	@JsonBackReference
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "role")
	public Set<RoleAuthRelation> getRoleAuthRelations() {
		return this.roleAuthRelations;
	}

	public void setRoleAuthRelations(Set<RoleAuthRelation> roleAuthRelations) {
		this.roleAuthRelations = roleAuthRelations;
	}

	@Override
	public String toString() {
		return "Role [roleId=" + roleId + ", roleName=" + roleName + "]";
	}

}
