package com.jtdd.entity;
// Generated 2017-11-4 17:55:03 by Hibernate Tools 4.0.1.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Rules generated by hbm2java
 */
@Entity
@Table(name = "rules", catalog = "stms")
public class Rules implements java.io.Serializable {

	private Integer id;
	private String rulesName;
	private String rulesDescribe;
	private int rulesScore;
	private int rulesType;
	private int menuId;
	private int rulesGrade;
	private Set<TeamHoorMessage> teamHoorMessages = new HashSet<TeamHoorMessage>(0);
	private Set<Executes> executeses = new HashSet<Executes>(0);
	private Set<Honest> honests = new HashSet<Honest>(0);

	public Rules() {
	}

	public Rules(String rulesName, int rulesScore, int rulesType, int menuId, int rulesGrade) {
		this.rulesName = rulesName;
		this.rulesScore = rulesScore;
		this.rulesType = rulesType;
		this.menuId = menuId;
		this.rulesGrade = rulesGrade;
	}

	public Rules(String rulesName, String rulesDescribe, int rulesScore, int rulesType, int menuId, int rulesGrade,
			Set<TeamHoorMessage> teamHoorMessages, Set<Executes> executeses, Set<Honest> honests) {
		this.rulesName = rulesName;
		this.rulesDescribe = rulesDescribe;
		this.rulesScore = rulesScore;
		this.rulesType = rulesType;
		this.menuId = menuId;
		this.rulesGrade = rulesGrade;
		this.teamHoorMessages = teamHoorMessages;
		this.executeses = executeses;
		this.honests = honests;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "rules_name", nullable = false, length = 50)
	public String getRulesName() {
		return this.rulesName;
	}

	public void setRulesName(String rulesName) {
		this.rulesName = rulesName;
	}

	@Column(name = "rules_describe", length = 50)
	public String getRulesDescribe() {
		return this.rulesDescribe;
	}

	public void setRulesDescribe(String rulesDescribe) {
		this.rulesDescribe = rulesDescribe;
	}

	@Column(name = "rules_score", nullable = false)
	public int getRulesScore() {
		return this.rulesScore;
	}

	public void setRulesScore(int rulesScore) {
		this.rulesScore = rulesScore;
	}

	@Column(name = "rules_type", nullable = false)
	public int getRulesType() {
		return this.rulesType;
	}

	public void setRulesType(int rulesType) {
		this.rulesType = rulesType;
	}

	@Column(name = "menu_id")
	public int getMenuId() {
		return this.menuId;
	}

	public void setMenuId(int menuId) {
		this.menuId = menuId;
	}

	@Column(name = "rules_grade")
	public int getRulesGrade() {
		return this.rulesGrade;
	}

	public void setRulesGrade(int rulesGrade) {
		this.rulesGrade = rulesGrade;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "rules")
	public Set<TeamHoorMessage> getTeamHoorMessages() {
		return this.teamHoorMessages;
	}

	public void setTeamHoorMessages(Set<TeamHoorMessage> teamHoorMessages) {
		this.teamHoorMessages = teamHoorMessages;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "rules")
	public Set<Executes> getExecuteses() {
		return this.executeses;
	}

	public void setExecuteses(Set<Executes> executeses) {
		this.executeses = executeses;
	}
	
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "rules")
	public Set<Honest> getHonests() {
		return this.honests;
	}

	public void setHonests(Set<Honest> honests) {
		this.honests = honests;
	}

}
