package com.jtdd.entity;
// Generated 2017-11-4 17:55:03 by Hibernate Tools 4.0.1.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * SkillExamActivity generated by hbm2java
 */
@Entity
@Table(name = "skill_exam_activity", catalog = "stms")
public class SkillExamActivity implements java.io.Serializable {

	private Integer id;
	private RecordStatus recordStatus;
	private String studentNumber;
	private String studentName;
	private Date examTime;
	private String rulesId;
	private int menuId;
	private String address;
	private String certificateGrade;

	public SkillExamActivity() {
	}

	public SkillExamActivity(RecordStatus recordStatus, String studentNumber, String studentName, Date examTime,
			String rulesId, int menuId, String address, String certificateGrade) {
		this.recordStatus = recordStatus;
		this.studentNumber = studentNumber;
		this.studentName = studentName;
		this.examTime = examTime;
		this.rulesId = rulesId;
		this.menuId = menuId;
		this.address = address;
		this.certificateGrade = certificateGrade;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "status_id", nullable = false)
	public RecordStatus getRecordStatus() {
		return this.recordStatus;
	}

	public void setRecordStatus(RecordStatus recordStatus) {
		this.recordStatus = recordStatus;
	}

	@Column(name = "student_number", nullable = false, length = 50)
	public String getStudentNumber() {
		return this.studentNumber;
	}

	public void setStudentNumber(String studentNumber) {
		this.studentNumber = studentNumber;
	}

	@Column(name = "student_name", nullable = false, length = 50)
	public String getStudentName() {
		return this.studentName;
	}

	public void setStudentName(String studentName) {
		this.studentName = studentName;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "exam_time", nullable = false, length = 10)
	public Date getExamTime() {
		return this.examTime;
	}

	public void setExamTime(Date examTime) {
		this.examTime = examTime;
	}

	@Column(name = "rules_id", nullable = false, length = 50)
	public String getRulesId() {
		return this.rulesId;
	}

	public void setRulesId(String rulesId) {
		this.rulesId = rulesId;
	}

	@Column(name = "menu_id", nullable = false)
	public int getMenuId() {
		return this.menuId;
	}

	public void setMenuId(int menuId) {
		this.menuId = menuId;
	}

	@Column(name = "address", nullable = false, length = 50)
	public String getAddress() {
		return this.address;
	}

	public void setAddress(String address) {
		this.address = address;
	}

	@Column(name = "certificate_grade", nullable = false, length = 50)
	public String getCertificateGrade() {
		return this.certificateGrade;
	}

	public void setCertificateGrade(String certificateGrade) {
		this.certificateGrade = certificateGrade;
	}

}
