package com.jtdd.entity;
// Generated 2017-11-4 17:55:03 by Hibernate Tools 4.0.1.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * SkillActivity generated by hbm2java
 */
@Entity
@Table(name = "skill_activity", catalog = "stms")
public class SkillActivity implements java.io.Serializable {

	private Integer id;
	private RecordStatus recordStatus;
	private String studentNumber;
	private String studentName;
	private Date activityTime;
	private int activityTypeId;
	private String activityAddress;
	private int menuId;

	public SkillActivity() {
	}

	public SkillActivity(RecordStatus recordStatus, String studentNumber, String studentName, Date activityTime,
			int activityTypeId, String activityAddress, int menuId) {
		this.recordStatus = recordStatus;
		this.studentNumber = studentNumber;
		this.studentName = studentName;
		this.activityTime = activityTime;
		this.activityTypeId = activityTypeId;
		this.activityAddress = activityAddress;
		this.menuId = menuId;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "status_id", nullable = false)
	public RecordStatus getRecordStatus() {
		return this.recordStatus;
	}

	public void setRecordStatus(RecordStatus recordStatus) {
		this.recordStatus = recordStatus;
	}

	@Column(name = "student_number", nullable = false, length = 50)
	public String getStudentNumber() {
		return this.studentNumber;
	}

	public void setStudentNumber(String studentNumber) {
		this.studentNumber = studentNumber;
	}

	@Column(name = "student_name", nullable = false, length = 50)
	public String getStudentName() {
		return this.studentName;
	}

	public void setStudentName(String studentName) {
		this.studentName = studentName;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "activity_time", nullable = false, length = 10)
	public Date getActivityTime() {
		return this.activityTime;
	}

	public void setActivityTime(Date activityTime) {
		this.activityTime = activityTime;
	}

	@Column(name = "activity_type_id", nullable = false)
	public int getActivityTypeId() {
		return this.activityTypeId;
	}

	public void setActivityTypeId(int activityTypeId) {
		this.activityTypeId = activityTypeId;
	}

	@Column(name = "activity_address", nullable = false, length = 50)
	public String getActivityAddress() {
		return this.activityAddress;
	}

	public void setActivityAddress(String activityAddress) {
		this.activityAddress = activityAddress;
	}

	@Column(name = "menu_id", nullable = false)
	public int getMenuId() {
		return this.menuId;
	}

	public void setMenuId(int menuId) {
		this.menuId = menuId;
	}

}
