package com.jtdd.entity;
// Generated 2017-11-4 17:55:03 by Hibernate Tools 4.0.1.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;

import java.util.Set;

import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Transient;

/**
 * Student generated by hbm2java
 */
@Entity
@Table(name = "student", catalog = "stms")
public class Student implements java.io.Serializable {

	private Integer studentId;
	private String studentName;
	private String studentSex;
	private String studentNation;
	private String entranceYear;
	private int onlineYear;
	private String graduateYear;
	private String contactPhone;
	private String studentCard;
	private Integer studentClassId;
	private String studentEmail;
	private String studentImg;
	private String studentHometown;
	private int studentAllScoreId;
	private String studentNumber;
	private Integer studentMajorId;
	private Integer studentDepartementId;
	private StudentClass studentClass;

	private StudentDepartment studentDepartment;    
	
	@Transient
	public StudentClass getStudentClass() {
		return studentClass;
	}

	public void setStudentClass(StudentClass studentClass) {
		this.studentClass = studentClass;
	}
	
	
	@Transient
	public StudentDepartment getStudentDepartment() {
		return studentDepartment;
	}

	public void setStudentDepartment(StudentDepartment studentDepartment) {
		this.studentDepartment = studentDepartment;
	}

	public Student() {
	}

	public Student(String studentName, String studentSex, String studentNation, String entranceYear, int onlineYear,
			String graduateYear, String contactPhone, String studentCard, Integer studentClassId, int studentAllScoreId,
			String studentNumber) {
		this.studentName = studentName;
		this.studentSex = studentSex;
		this.studentNation = studentNation;
		this.entranceYear = entranceYear;
		this.onlineYear = onlineYear;
		this.graduateYear = graduateYear;
		this.contactPhone = contactPhone;
		this.studentCard = studentCard;
		this.studentClassId = studentClassId;
		this.studentAllScoreId = studentAllScoreId;
		this.studentNumber = studentNumber;
	}

	public Student(String studentName, String studentSex, String studentNation, String entranceYear, int onlineYear,
			String graduateYear, String contactPhone, String studentCard, Integer studentClassId, String studentEmail,
			String studentImg, String studentHometown, int studentAllScoreId, String studentNumber) {
		this.studentName = studentName;
		this.studentSex = studentSex;
		this.studentNation = studentNation;
		this.entranceYear = entranceYear;
		this.onlineYear = onlineYear;
		this.graduateYear = graduateYear;
		this.contactPhone = contactPhone;
		this.studentCard = studentCard;
		this.studentClassId = studentClassId;
		this.studentEmail = studentEmail;
		this.studentImg = studentImg;
		this.studentHometown = studentHometown;
		this.studentAllScoreId = studentAllScoreId;
		this.studentNumber = studentNumber;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "student_id", unique = true, nullable = false)
	public Integer getStudentId() {
		return this.studentId;
	}

	public void setStudentId(Integer studentId) {
		this.studentId = studentId;
	}

	@Column(name = "student_name", nullable = false, length = 12)
	public String getStudentName() {
		return this.studentName;
	}

	public void setStudentName(String studentName) {
		this.studentName = studentName;
	}

	@Column(name = "student_sex", nullable = false, length = 2)
	public String getStudentSex() {
		return this.studentSex;
	}

	public void setStudentSex(String studentSex) {
		this.studentSex = studentSex;
	}

	@Column(name = "student_nation", nullable = false, length = 20)
	public String getStudentNation() {
		return this.studentNation;
	}

	public void setStudentNation(String studentNation) {
		this.studentNation = studentNation;
	}

	@Column(name = "entrance_year", nullable = false, length = 4)
	public String getEntranceYear() {
		return this.entranceYear;
	}

	public void setEntranceYear(String entranceYear) {
		this.entranceYear = entranceYear;
	}

	@Column(name = "online_year", nullable = false)
	public int getOnlineYear() {
		return this.onlineYear;
	}

	public void setOnlineYear(int onlineYear) {
		this.onlineYear = onlineYear;
	}

	@Column(name = "graduate_year", nullable = false, length = 50)
	public String getGraduateYear() {
		return this.graduateYear;
	}

	public void setGraduateYear(String graduateYear) {
		this.graduateYear = graduateYear;
	}

	@Column(name = "contact_phone", nullable = false, length = 11)
	public String getContactPhone() {
		return this.contactPhone;
	}

	public void setContactPhone(String contactPhone) {
		this.contactPhone = contactPhone;
	}

	@Column(name = "student_card", nullable = false, length = 18)
	public String getStudentCard() {
		return this.studentCard;
	}

	public void setStudentCard(String studentCard) {
		this.studentCard = studentCard;
	}

	@Column(name = "student_class_id", nullable = false, length = 11)
	public Integer getStudentClassId() {
		return this.studentClassId;
	}

	public void setStudentClassId(Integer studentClassId) {
		this.studentClassId = studentClassId;
	}

	@Column(name = "student_email", length = 50)
	public String getStudentEmail() {
		return this.studentEmail;
	}

	public void setStudentEmail(String studentEmail) {
		this.studentEmail = studentEmail;
	}

	@Column(name = "student_img", length = 50)
	public String getStudentImg() {
		return this.studentImg;
	}

	public void setStudentImg(String studentImg) {
		this.studentImg = studentImg;
	}

	@Column(name = "student_hometown", length = 50)
	public String getStudentHometown() {
		return this.studentHometown;
	}

	public void setStudentHometown(String studentHometown) {
		this.studentHometown = studentHometown;
	}

	@Column(name = "student_all_score_id", nullable = false)
	public int getStudentAllScoreId() {
		return this.studentAllScoreId;
	}

	public void setStudentAllScoreId(int studentAllScoreId) {
		this.studentAllScoreId = studentAllScoreId;
	}

	@Column(name = "student_number", nullable = false, length = 50)
	public String getStudentNumber() {
		return this.studentNumber;
	}

	public void setStudentNumber(String studentNumber) {
		this.studentNumber = studentNumber;
	}

	@Column(name = "student_major_id", nullable = false, length = 11)
	public Integer getStudentMajorId() {
		return studentMajorId;
	}

	public void setStudentMajorId(Integer studentMajorId) {
		this.studentMajorId = studentMajorId;
	}

	@Column(name = "student_deparatment_id", nullable = false, length = 11)
	public Integer getStudentDepartementId() {
		return studentDepartementId;
	}

	public void setStudentDepartementId(Integer studentDepartementId) {
		this.studentDepartementId = studentDepartementId;
	}
	
	
	
	
	


}
