package com.jtdd.entity;
// Generated 2017-11-4 17:55:03 by Hibernate Tools 4.0.1.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

import org.codehaus.jackson.annotate.JsonManagedReference;

import com.fasterxml.jackson.annotation.JsonBackReference;

/**
 * StudentDepartment generated by hbm2java
 */
@Entity
@Table(name = "student_department", catalog = "stms")
public class StudentDepartment implements java.io.Serializable {

	private Integer id;
	private String name;
	private int majorNumbers;
	@JsonBackReference
	private Set<Major> majors = new HashSet<Major>(0);

	public StudentDepartment() {
	}

	public StudentDepartment(String name, int majorNumbers) {
		this.name = name;
		this.majorNumbers = majorNumbers;
	}

	public StudentDepartment(String name, int majorNumbers, Set<Major> majors) {
		this.name = name;
		this.majorNumbers = majorNumbers;
		this.majors = majors;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "name", nullable = false, length = 50)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "major_numbers", nullable = false)
	public int getMajorNumbers() {
		return this.majorNumbers;
	}

	public void setMajorNumbers(int majorNumbers) {
		this.majorNumbers = majorNumbers;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "studentDepartment")
	public Set<Major> getMajors() {
		return this.majors;
	}

	public void setMajors(Set<Major> majors) {
		this.majors = majors;
	}

	@Override
	public String toString() {
		return "StudentDepartment [id=" + id + ", name=" + name + ", majorNumbers=" + majorNumbers + "]";
	}

}
