package com.jtdd.entity;
// Generated 2017-11-4 17:55:03 by Hibernate Tools 4.0.1.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * SysConfig generated by hbm2java
 */
@Entity
@Table(name = "sys_config", catalog = "stms")
public class SysConfig implements java.io.Serializable {

	private Integer sysId;
	private String sysName;
	private String sysValue;
	private String sysDescribe;

	public SysConfig() {
	}

	public SysConfig(String sysName, String sysValue, String sysDescribe) {
		this.sysName = sysName;
		this.sysValue = sysValue;
		this.sysDescribe = sysDescribe;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "sys_id", unique = true, nullable = false)
	public Integer getSysId() {
		return this.sysId;
	}

	public void setSysId(Integer sysId) {
		this.sysId = sysId;
	}

	@Column(name = "sys_name", nullable = false, length = 50)
	public String getSysName() {
		return this.sysName;
	}

	public void setSysName(String sysName) {
		this.sysName = sysName;
	}

	@Column(name = "sys_value", nullable = false, length = 50)
	public String getSysValue() {
		return this.sysValue;
	}

	public void setSysValue(String sysValue) {
		this.sysValue = sysValue;
	}

	@Column(name = "sys_describe", nullable = false, length = 50)
	public String getSysDescribe() {
		return this.sysDescribe;
	}

	public void setSysDescribe(String sysDescribe) {
		this.sysDescribe = sysDescribe;
	}

}
