package com.jtdd.entity;
// Generated 2017-11-4 17:55:03 by Hibernate Tools 4.0.1.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Teacher generated by hbm2java
 */
@Entity
@Table(name = "teacher", catalog = "stms")
public class Teacher implements java.io.Serializable {

	private Integer teacherId;
	private String teacherName;
	private String teacherSex;
	private String teacherNation;
	private String workTime;
	private String teacherEducation;
	private String positionalTitles;
	private String contactPhone;
	private String teacherCard;
	private int teacherRole;
	private String teacherImg;
	private String teacherNumber;
	private Set<TeacherClass> teacherClasses = new HashSet<TeacherClass>(0);

	public Teacher() {
	}

	public Teacher(String teacherName, String teacherSex, String teacherNation, String workTime,
			String teacherEducation, String positionalTitles, String contactPhone, String teacherCard, int teacherRole,
			String teacherNumber) {
		this.teacherName = teacherName;
		this.teacherSex = teacherSex;
		this.teacherNation = teacherNation;
		this.workTime = workTime;
		this.teacherEducation = teacherEducation;
		this.positionalTitles = positionalTitles;
		this.contactPhone = contactPhone;
		this.teacherCard = teacherCard;
		this.teacherRole = teacherRole;
		this.teacherNumber = teacherNumber;
	}

	public Teacher(String teacherName, String teacherSex, String teacherNation, String workTime,
			String teacherEducation, String positionalTitles, String contactPhone, String teacherCard, int teacherRole,
			String teacherImg, String teacherNumber, Set<TeacherClass> teacherClasses) {
		this.teacherName = teacherName;
		this.teacherSex = teacherSex;
		this.teacherNation = teacherNation;
		this.workTime = workTime;
		this.teacherEducation = teacherEducation;
		this.positionalTitles = positionalTitles;
		this.contactPhone = contactPhone;
		this.teacherCard = teacherCard;
		this.teacherRole = teacherRole;
		this.teacherImg = teacherImg;
		this.teacherNumber = teacherNumber;
		this.teacherClasses = teacherClasses;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "teacher_id", unique = true, nullable = false)
	public Integer getTeacherId() {
		return this.teacherId;
	}

	public void setTeacherId(Integer teacherId) {
		this.teacherId = teacherId;
	}

	@Column(name = "teacher_name", nullable = false, length = 12)
	public String getTeacherName() {
		return this.teacherName;
	}

	public void setTeacherName(String teacherName) {
		this.teacherName = teacherName;
	}

	@Column(name = "teacher_sex", nullable = false, length = 2)
	public String getTeacherSex() {
		return this.teacherSex;
	}

	public void setTeacherSex(String teacherSex) {
		this.teacherSex = teacherSex;
	}

	@Column(name = "teacher_nation", nullable = false, length = 20)
	public String getTeacherNation() {
		return this.teacherNation;
	}

	public void setTeacherNation(String teacherNation) {
		this.teacherNation = teacherNation;
	}

	@Column(name = "work_time", nullable = false, length = 4)
	public String getWorkTime() {
		return this.workTime;
	}

	public void setWorkTime(String workTime) {
		this.workTime = workTime;
	}

	@Column(name = "teacher_education", nullable = false, length = 10)
	public String getTeacherEducation() {
		return this.teacherEducation;
	}

	public void setTeacherEducation(String teacherEducation) {
		this.teacherEducation = teacherEducation;
	}

	@Column(name = "positional_titles", nullable = false, length = 6)
	public String getPositionalTitles() {
		return this.positionalTitles;
	}

	public void setPositionalTitles(String positionalTitles) {
		this.positionalTitles = positionalTitles;
	}

	@Column(name = "contact_phone", nullable = false, length = 11)
	public String getContactPhone() {
		return this.contactPhone;
	}

	public void setContactPhone(String contactPhone) {
		this.contactPhone = contactPhone;
	}

	@Column(name = "teacher_card", nullable = false, length = 18)
	public String getTeacherCard() {
		return this.teacherCard;
	}

	public void setTeacherCard(String teacherCard) {
		this.teacherCard = teacherCard;
	}

	@Column(name = "teacher_role", nullable = false)
	public int getTeacherRole() {
		return this.teacherRole;
	}

	public void setTeacherRole(int teacherRole) {
		this.teacherRole = teacherRole;
	}

	@Column(name = "teacher_img", length = 50)
	public String getTeacherImg() {
		return this.teacherImg;
	}

	public void setTeacherImg(String teacherImg) {
		this.teacherImg = teacherImg;
	}

	@Column(name = "teacher_number", nullable = false, length = 50)
	public String getTeacherNumber() {
		return this.teacherNumber;
	}

	public void setTeacherNumber(String teacherNumber) {
		this.teacherNumber = teacherNumber;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "teacher")
	public Set<TeacherClass> getTeacherClasses() {
		return this.teacherClasses;
	}

	public void setTeacherClasses(Set<TeacherClass> teacherClasses) {
		this.teacherClasses = teacherClasses;
	}

}
