package com.jtdd.entity;
// Generated 2017-11-4 17:55:03 by Hibernate Tools 4.0.1.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * TeamHoorMessage generated by hbm2java
 */
@Entity
@Table(name = "team_hoor_message", catalog = "stms")
public class TeamHoorMessage implements java.io.Serializable {

	private Integer id;
	private Rules rules;
	private RecordStatus recordStatus;
	private String studentNumber;
	private String remark;
	private int menuId;
	private Date hoorTime;

	public TeamHoorMessage() {
	}

	public TeamHoorMessage(Rules rules, RecordStatus recordStatus, String studentNumber, int menuId, Date hoorTime) {
		this.rules = rules;
		this.recordStatus = recordStatus;
		this.studentNumber = studentNumber;
		this.menuId = menuId;
		this.hoorTime = hoorTime;
	}

	public TeamHoorMessage(Rules rules, RecordStatus recordStatus, String studentNumber, String remark, int menuId,
			Date hoorTime) {
		this.rules = rules;
		this.recordStatus = recordStatus;
		this.studentNumber = studentNumber;
		this.remark = remark;
		this.menuId = menuId;
		this.hoorTime = hoorTime;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "rules_id", nullable = false)
	public Rules getRules() {
		return this.rules;
	}

	public void setRules(Rules rules) {
		this.rules = rules;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "status_id", nullable = false)
	public RecordStatus getRecordStatus() {
		return this.recordStatus;
	}

	public void setRecordStatus(RecordStatus recordStatus) {
		this.recordStatus = recordStatus;
	}

	@Column(name = "student_number", nullable = false, length = 50)
	public String getStudentNumber() {
		return this.studentNumber;
	}

	public void setStudentNumber(String studentNumber) {
		this.studentNumber = studentNumber;
	}

	@Column(name = "remark", length = 100)
	public String getRemark() {
		return this.remark;
	}

	public void setRemark(String remark) {
		this.remark = remark;
	}

	@Column(name = "menu_id", nullable = false)
	public int getMenuId() {
		return this.menuId;
	}

	public void setMenuId(int menuId) {
		this.menuId = menuId;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "hoor_time", nullable = false, length = 10)
	public Date getHoorTime() {
		return this.hoorTime;
	}

	public void setHoorTime(Date hoorTime) {
		this.hoorTime = hoorTime;
	}

}
