package com.jtdd.entity;
// Generated 2017-11-4 17:55:03 by Hibernate Tools 4.0.1.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;

import java.util.List;

import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Transient;

import org.codehaus.jackson.annotate.JsonManagedReference;

import com.fasterxml.jackson.annotation.JsonBackReference;

/**
 * UserDetailed generated by hbm2java
 */
@Entity
@Table(name = "user_detailed", catalog = "stms")
public class UserDetailed implements java.io.Serializable {

	private Integer userId;
	private Role role;
	private String userNumber;
	private String userName;
	private String userEmail;
	private String contactPhone;
	private String userImg;
	

	public UserDetailed() {
	}

	public UserDetailed(Role role, String userNumber, String userName, String userEmail, String contactPhone) {
		this.role = role;
		this.userNumber = userNumber;
		this.userName = userName;
		this.userEmail = userEmail;
		this.contactPhone = contactPhone;
	}

	public UserDetailed(Role role, String userNumber, String userName, String userEmail, String contactPhone,
			String userImg) {
		this.role = role;
		this.userNumber = userNumber;
		this.userName = userName;
		this.userEmail = userEmail;
		this.contactPhone = contactPhone;
		this.userImg = userImg;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "user_id", unique = true, nullable = false)
	public Integer getUserId() {
		return this.userId;
	}

	public void setUserId(Integer userId) {
		this.userId = userId;
	}
	@JsonManagedReference
	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "user_role", nullable = false)
	public Role getRole() {
		return this.role;
	}

	public void setRole(Role role) {
		this.role = role;
	}

	@Column(name = "user_number", nullable = false, length = 50)
	public String getUserNumber() {
		return this.userNumber;
	}

	public void setUserNumber(String userNumber) {
		this.userNumber = userNumber;
	}

	@Column(name = "user_name", nullable = false, length = 50)
	public String getUserName() {
		return this.userName;
	}

	public void setUserName(String userName) {
		this.userName = userName;
	}

	@Column(name = "user_email", nullable = false, length = 50)
	public String getUserEmail() {
		return this.userEmail;
	}

	public void setUserEmail(String userEmail) {
		this.userEmail = userEmail;
	}

	@Column(name = "contact_phone", nullable = false, length = 11)
	public String getContactPhone() {
		return this.contactPhone;
	}

	public void setContactPhone(String contactPhone) {
		this.contactPhone = contactPhone;
	}

	@Column(name = "user_img", length = 50)
	public String getUserImg() {
		return this.userImg;
	}

	public void setUserImg(String userImg) {
		this.userImg = userImg;
	}

}
